// src/constants/adminPermissions.js
// Khớp với enum AdminPermission ở backend (com.example.sales.constant.AdminPermission).
export const ADMIN_PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  SHOP_VIEW: "SHOP_VIEW",
  SHOP_MANAGE: "SHOP_MANAGE",

  USER_VIEW: "USER_VIEW",
  USER_MANAGE: "USER_MANAGE",

  BILLING_VIEW: "BILLING_VIEW",
  BILLING_MANAGE: "BILLING_MANAGE",

  CATALOG_MANAGE: "CATALOG_MANAGE",

  SUPPORT_VIEW: "SUPPORT_VIEW",
  SUPPORT_MANAGE: "SUPPORT_MANAGE",

  BROADCAST_SEND: "BROADCAST_SEND",

  AUDIT_VIEW: "AUDIT_VIEW",

  IMPERSONATE: "IMPERSONATE",

  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
});

export const ADMIN_PERM = ADMIN_PERMISSIONS;

/** Preset bundles tương ứng backend (AdminPermission.Preset). */
export const ADMIN_PERMISSION_PRESETS = Object.freeze({
  SUPER_ADMIN: Object.values(ADMIN_PERMISSIONS),
  SUPPORT_ADMIN: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.SUPPORT_VIEW,
    ADMIN_PERMISSIONS.SUPPORT_MANAGE,
    ADMIN_PERMISSIONS.SHOP_VIEW,
    ADMIN_PERMISSIONS.USER_VIEW,
  ],
  BILLING_ADMIN: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.BILLING_VIEW,
    ADMIN_PERMISSIONS.BILLING_MANAGE,
    ADMIN_PERMISSIONS.SHOP_VIEW,
    ADMIN_PERMISSIONS.USER_VIEW,
  ],
  CONTENT_ADMIN: [
    ADMIN_PERMISSIONS.DASHBOARD_VIEW,
    ADMIN_PERMISSIONS.CATALOG_MANAGE,
    ADMIN_PERMISSIONS.BROADCAST_SEND,
  ],
});
