// src/constants/shopPermissions.js
// Chuỗi quyền khớp enum Permission ở backend (com.example.sales.constant.Permission)
export const SHOP_PERMISSIONS = Object.freeze({
  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_IMPORT: "PRODUCT_IMPORT",
  PRODUCT_EXPORT: "PRODUCT_EXPORT",
  PRODUCT_UPDATE_STATUS: "PRODUCT_UPDATE_STATUS",
  PRODUCT_VIEW_LOW_STOCK: "PRODUCT_VIEW_LOW_STOCK",

  ORDER_VIEW: "ORDER_VIEW",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_CANCEL: "ORDER_CANCEL",
  ORDER_PAYMENT_CONFIRM: "ORDER_PAYMENT_CONFIRM",

  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  PROMOTION_VIEW: "PROMOTION_VIEW",
  PROMOTION_CREATE: "PROMOTION_CREATE",
  PROMOTION_UPDATE: "PROMOTION_UPDATE",
  PROMOTION_DELETE: "PROMOTION_DELETE",

  TABLE_VIEW: "TABLE_VIEW",
  TABLE_CREATE: "TABLE_CREATE",
  TABLE_UPDATE: "TABLE_UPDATE",
  TABLE_DELETE: "TABLE_DELETE",

  SHOP_VIEW: "SHOP_VIEW",
  SHOP_UPDATE: "SHOP_UPDATE",
  SHOP_DELETE: "SHOP_DELETE",
  SHOP_MANAGE: "SHOP_MANAGE",

  SHOP_USER_VIEW: "SHOP_USER_VIEW",
  SHOP_USER_CREATE: "SHOP_USER_CREATE",
  SHOP_USER_UPDATE: "SHOP_USER_UPDATE",
  SHOP_USER_DELETE: "SHOP_USER_DELETE",

  BRANCH_VIEW: "BRANCH_VIEW",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_MANAGE: "BRANCH_MANAGE",

  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  REPORT_VIEW: "REPORT_VIEW",

  SUPPORT_VIEW: "SUPPORT_VIEW",
  SUPPORT_MANAGE: "SUPPORT_MANAGE",
});

export const PERM = SHOP_PERMISSIONS;
