export const WebSocketMessageTypes = {
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  PASSWORD_RESET: "PASSWORD_RESET",
  NOTIFICATION: "NOTIFICATION",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_DELETED: "ORDER_DELETED",

  TABLE_CREATED: "TABLE_CREATED",
  TABLE_UPDATED: "TABLE_UPDATED",
  TABLE_DELETED: "TABLE_DELETED",
  TABLE_STATUS_CHANGED: "TABLE_STATUS_CHANGED",
  TABLE_ASSIGNED: "TABLE_ASSIGNED",

  PAYMENT_SUCCEEDED: "PAYMENT_SUCCEEDED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
};
