export const WebSocketMessageTypes = {
    EMAIL_VERIFIED: "EMAIL_VERIFIED",
    PASSWORD_RESET: "PASSWORD_RESET",
    ORDER_CREATED: "ORDER_CREATED",
    ORDER_UPDATED: "ORDER_UPDATED",
    NOTIFICATION: "NOTIFICATION"
};
